import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import ScrollToTop from '../components/ScrollToTop';
import { AuthProvider } from '../store/AuthContext';
import { AdminProvider } from '../store/AdminContext';
import ProtectedRoute from '../components/ProtectedRoute';
import AdminGuard from '../pages/Admin/AdminGuard';
import Home from '../pages/Home/Home'; import About from '../pages/About/About'; import Services from '../pages/Services/Services'; import Packages from '../pages/Packages/Packages'; import GalleryPage from '../pages/GalleryPage/GalleryPage'; import Contact from '../pages/Contact/Contact'; import Booking from '../pages/Booking/Booking';
import Login from '../pages/Auth/Login'; import Register from '../pages/Auth/Register'; import ForgotPassword from '../pages/Auth/ForgotPassword'; import ResetPassword from '../pages/Auth/ResetPassword';
import Dashboard from '../pages/Dashboard/Dashboard'; import UserBookings from '../pages/Dashboard/Bookings'; import BookingDetail from '../pages/Dashboard/BookingDetail'; import Reschedule from '../pages/Dashboard/Reschedule'; import Payments from '../pages/Dashboard/Payments'; import Profile from '../pages/Dashboard/Profile'; import AccountSettings from '../pages/Dashboard/Settings'; import PublicTherapists from '../pages/Therapists/Therapists'; import TherapistDetail from '../pages/Therapists/TherapistDetail'; import ServiceDetail from '../pages/ServiceDetail/ServiceDetail';
import AdminLogin from '../pages/Admin/AdminLogin'; import AdminBookingOption from '../pages/Admin/AdminBookingOption'; import AdminOverview from '../pages/Admin/AdminOverview'; import AdminUserDetail from '../pages/Admin/AdminUserDetail'; import AdminAvailability from '../pages/Admin/AdminAvailability'; import AdminBookingDetail from '../pages/Admin/AdminBookingDetail'; import AdminExtraServices from '../pages/Admin/AdminExtraServices'; import { Users, Bookings, Payments as AdminPayments, Therapists, Services as AdminServices, Settings, ActivityLogs } from '../pages/Admin/AdminListPages';

export default function AppRoutes() {
    return <BrowserRouter><ScrollToTop /><AuthProvider><AdminProvider><Routes>
        <Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/services" element={<Services />} /><Route path="/services/:id" element={<ServiceDetail />} /><Route path="/therapists" element={<PublicTherapists />} /><Route path="/therapists/:id" element={<TherapistDetail />} /><Route path="/packages" element={<Packages />} /><Route path="/gallery" element={<GalleryPage />} /><Route path="/contact" element={<Contact />} /><Route path="/booking" element={<Booking />} />
        <Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/forgot-password" element={<ForgotPassword />} /><Route path="/reset-password" element={<ResetPassword />} />
        <Route path="/dashboard" element={<ProtectedRoute><Dashboard /></ProtectedRoute>} /><Route path="/dashboard/bookings" element={<ProtectedRoute><UserBookings /></ProtectedRoute>} /><Route path="/dashboard/bookings/:id" element={<ProtectedRoute><BookingDetail /></ProtectedRoute>} /><Route path="/dashboard/bookings/:id/reschedule" element={<ProtectedRoute><Reschedule /></ProtectedRoute>} /><Route path="/dashboard/payments" element={<ProtectedRoute><Payments /></ProtectedRoute>} /><Route path="/dashboard/profile" element={<ProtectedRoute><Profile /></ProtectedRoute>} /><Route path="/dashboard/settings" element={<ProtectedRoute><AccountSettings /></ProtectedRoute>} />
        <Route path="/admin/login" element={<AdminLogin />} /><Route path="/admin" element={<AdminGuard><AdminOverview /></AdminGuard>} /><Route path="/admin/users" element={<AdminGuard><Users /></AdminGuard>} /><Route path="/admin/users/:id" element={<AdminGuard><AdminUserDetail /></AdminGuard>} /><Route path="/admin/bookings" element={<AdminGuard><Bookings /></AdminGuard>} /><Route path="/admin/bookings/:id" element={<AdminGuard><AdminBookingDetail /></AdminGuard>} /><Route path="/admin/payments" element={<AdminGuard><AdminPayments /></AdminGuard>} /><Route path="/admin/therapists" element={<AdminGuard><Therapists /></AdminGuard>} /><Route path="/admin/services" element={<AdminGuard><AdminServices /></AdminGuard>} /><Route path="/admin/extra-services" element={<AdminGuard><AdminExtraServices /></AdminGuard>} /><Route path="/admin/booking-payment" element={<AdminGuard><AdminBookingOption /></AdminGuard>} /><Route path="/admin/settings" element={<AdminGuard><Settings /></AdminGuard>} /><Route path="/admin/availability" element={<AdminGuard><AdminAvailability /></AdminGuard>} /><Route path="/admin/activity-logs" element={<AdminGuard><ActivityLogs /></AdminGuard>} />
        <Route path="*" element={<Navigate to="/" replace />} />
    </Routes></AdminProvider></AuthProvider></BrowserRouter>
}
