import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import AuthLayout from './AuthLayout';
import Field from '../../components/Field';
import PasswordField from '../../components/PasswordField';
import SubmitButton from '../shared/SubmitButton';
import GoogleSignIn from '../../components/GoogleSignIn';
import { useAuth } from '../../hooks/useAuth';

export default function Login(){const [form,setForm]=useState({email:'',password:''});const [error,setError]=useState('');const [loading,setLoading]=useState(false);const {login}=useAuth();const navigate=useNavigate();const location=useLocation();const returnTo=new URLSearchParams(location.search).get('returnTo')||'/dashboard';const submit=async(e)=>{e.preventDefault();setError('');setLoading(true);try{await login(form);navigate(returnTo,{replace:true})}catch(err){setError(err.message)}finally{setLoading(false)}};return <AuthLayout><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Welcome back.</h2><p className="mt-3 text-sm leading-7 text-[#7c725f]">Enter your details to manage your Aviana experience.</p><form onSubmit={submit} className="mt-10 space-y-7"><Field label="Email" name="email" type="email" autoComplete="email" required value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/><PasswordField label="Password" name="password" autoComplete="current-password" required minLength={8} value={form.password} onChange={e=>setForm(v=>({...v,password:e.target.value}))}/>{error&&<p role="alert" className="border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<SubmitButton loading={loading}>{loading?'SIGNING IN…':'SIGN IN'}</SubmitButton></form><GoogleSignIn onSuccess={async credential=>{try{const r=await import('../../services/api').then(m=>m.api.post('/auth/google',{idToken:credential}));navigate(returnTo,{replace:true});void r}catch(err){setError(err.message)}}} onError={setError}/><div className="mt-7 flex flex-wrap justify-between gap-3 text-xs text-[#7c725f]"><Link to="/forgot-password" className="hover:text-[#b08d57]">Forgot password?</Link><Link to={`/register?returnTo=${encodeURIComponent(returnTo)}`} className="hover:text-[#b08d57]">Create account</Link></div></AuthLayout>}
