import { useMemo, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import AuthLayout from './AuthLayout';
import Field from '../../components/Field';
import PasswordField from '../../components/PasswordField';
import SubmitButton from '../shared/SubmitButton';
import GoogleSignIn from '../../components/GoogleSignIn';
import { useAuth } from '../../hooks/useAuth';

function strength(password){let score=0;if(password.length>=8)score++;if(/[A-Z]/.test(password))score++;if(/[a-z]/.test(password))score++;if(/\d/.test(password))score++;if(/[^A-Za-z0-9]/.test(password))score++;return score}
export default function Register(){const [form,setForm]=useState({fullName:'',email:'',phone:'',password:'',confirmPassword:''});const [error,setError]=useState('');const [loading,setLoading]=useState(false);const {register}=useAuth();const navigate=useNavigate();const location=useLocation();const returnTo=new URLSearchParams(location.search).get('returnTo')||'/dashboard';const level=useMemo(()=>strength(form.password),[form.password]);const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));const submit=async e=>{e.preventDefault();setError('');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');setLoading(true);try{await register({fullName:form.fullName,email:form.email,phone:form.phone,password:form.password});navigate(returnTo,{replace:true})}catch(err){setError(err.message)}finally{setLoading(false)}};return <AuthLayout><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Begin your account.</h2><p className="mt-3 text-sm leading-7 text-[#7c725f]">One account keeps your reservations, receipts and history together.</p><form onSubmit={submit} className="mt-10 space-y-7"><Field label="Full name" name="fullName" autoComplete="name" required value={form.fullName} onChange={change}/><Field label="Email" name="email" type="email" autoComplete="email" required value={form.email} onChange={change}/><Field label="Phone" name="phone" type="tel" autoComplete="tel" required value={form.phone} onChange={change}/><PasswordField label="Password" name="password" autoComplete="new-password" required minLength={8} value={form.password} onChange={change}/>{form.password&&<div className="flex items-center gap-2"><div className="grid flex-1 grid-cols-5 gap-1">{Array.from({length:5}).map((_,i)=><span key={i} className={`h-1 rounded-full ${i<level?'bg-[#b08d57]':'bg-[#e2dbd1]'}`}/>)}</div><span className="text-[10px] uppercase tracking-[0.13em] text-[#8f8678]">{level<3?'Gentle':'Strong'}</span></div>}<PasswordField label="Confirm password" name="confirmPassword" autoComplete="new-password" required minLength={8} value={form.confirmPassword} onChange={change}/>{error&&<p role="alert" className="border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<label className="flex items-start gap-3 text-xs leading-5 text-[#7c725f]"><input type="checkbox" required className="mt-1"/>I agree to use Aviana services under the applicable booking and cancellation terms.</label><SubmitButton loading={loading}>{loading?'CREATING ACCOUNT…':'CREATE ACCOUNT'}</SubmitButton></form><GoogleSignIn onSuccess={async credential=>{try{await import('../../services/api').then(m=>m.api.post('/auth/google',{idToken:credential}));navigate(returnTo,{replace:true})}catch(err){setError(err.message)}}} onError={setError}/><div className="mt-7 text-xs text-[#7c725f]">Already registered? <Link to={`/login?returnTo=${encodeURIComponent(returnTo)}`} className="text-[#b08d57]">Sign in</Link></div></AuthLayout>}
