import { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import TreatmentCard from './TreatmentCard';
import { api } from '../../../services/api';

export default function FeaturedTreatments() {
  const [services, setServices] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled=false; api.get('/services').then(r=>{if(!cancelled)setServices((r.services||[]).slice(0,4))}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false)}); return ()=>{cancelled=true}; }, []);
  return <section className="bg-[#fdfcf9] px-6 py-24 sm:px-10 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl"><motion.div initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.3}} transition={{duration:.8}} className="mb-14 text-center"><div className="mx-auto mb-5 h-px w-24 bg-[#c9a45e]"/><p className="text-[10px] font-medium tracking-[0.4em] text-[#b08d57]">OUR SIGNATURE EXPERIENCES</p><h2 className="mt-5 font-serif text-4xl font-light uppercase tracking-[0.08em] text-[#171512] sm:text-5xl">Featured Treatments</h2><p className="mx-auto mt-6 max-w-2xl text-sm font-light leading-7 text-[#918b84] sm:text-base sm:leading-8">Thoughtfully crafted rituals designed to relax the body, quiet the mind, and restore your natural sense of balance.</p></motion.div>{loading?<div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="animate-pulse border border-black/5 bg-white p-3"><div className="aspect-[4/3] bg-[#eee8df]"/><div className="space-y-3 p-4"><div className="h-5 w-2/3 bg-[#eee8df]"/><div className="h-3 w-full bg-[#eee8df]"/></div></div>)}</div>:<div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{services.map((service,index)=><motion.div key={service._id} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.7,delay:index*.12}}><TreatmentCard treatment={service}/></motion.div>)}</div>}<motion.div initial={{opacity:0}} whileInView={{opacity:1}} viewport={{once:true}} transition={{delay:.5,duration:.8}} className="mt-16 text-center"><Link to="/services" className="inline-flex items-center gap-3 border-b border-[#b08d57] pb-2 text-[10px] font-medium tracking-[0.25em] text-[#8f7042] transition-colors hover:text-[#b08d57]">VIEW ALL TREATMENTS<span className="text-base">→</span></Link></motion.div></div></section>;
}
