import { Router } from 'express';
import * as admin from '../controllers/adminController.js';
import { protectAdmin } from '../middleware/adminAuth.js';
import { imageUpload } from '../utils/upload.js';
import { createExtraService, deleteExtraService, listAdminExtraServices, setExtraServiceActive, updateExtraService, uploadExtraServiceImage } from '../controllers/extraServiceController.js';

const router = Router();
router.post('/auth/login', admin.adminLogin);
router.get('/auth/me', protectAdmin, admin.adminMe);
router.post('/auth/logout', protectAdmin, admin.adminLogout);
router.get('/dashboard', protectAdmin, admin.dashboard);
router.get('/users', protectAdmin, admin.listUsers);
router.get('/users/:id', protectAdmin, admin.userDetail);
router.patch('/users/:id/block', protectAdmin, (req, res, next) => { req.body.blocked = true; admin.setUserBlocked(req, res, next); });
router.patch('/users/:id/unblock', protectAdmin, (req, res, next) => { req.body.blocked = false; admin.setUserBlocked(req, res, next); });
router.delete('/users/:id', protectAdmin, admin.deleteUser);
router.get('/bookings', protectAdmin, admin.listBookings);
router.get('/bookings/:id', protectAdmin, admin.bookingDetail);
router.post('/bookings/:id/remaining-payment', protectAdmin, admin.recordRemainingPayment);
router.patch('/bookings/:id/status', protectAdmin, admin.updateBookingStatus);
router.get('/payments', protectAdmin, admin.listPayments);
router.post('/payments/:id/refund', protectAdmin, admin.refundPayment);
router.get('/therapists', protectAdmin, admin.listTherapists);
router.post('/therapists', protectAdmin, admin.createTherapist);
router.patch('/therapists/:id', protectAdmin, admin.updateTherapist);
router.patch('/therapists/:id/status', protectAdmin, admin.setTherapistActive);
router.delete('/therapists/:id', protectAdmin, admin.deleteTherapist);
router.post('/therapists/:id/image', protectAdmin, imageUpload.single('image'), admin.uploadTherapistImage);
router.get('/extra-services', protectAdmin, listAdminExtraServices);
router.post('/extra-services', protectAdmin, createExtraService);
router.patch('/extra-services/:id', protectAdmin, updateExtraService);
router.put('/extra-services/:id', protectAdmin, updateExtraService);
router.patch('/extra-services/:id/status', protectAdmin, setExtraServiceActive);
router.delete('/extra-services/:id', protectAdmin, deleteExtraService);
router.post('/extra-services/:id/image', protectAdmin, imageUpload.single('image'), uploadExtraServiceImage);
router.get('/services', protectAdmin, admin.listServices);
router.post('/services', protectAdmin, admin.createService);
router.patch('/services/:id', protectAdmin, admin.updateService);
router.patch('/services/:id/status', protectAdmin, admin.setServiceActive);
router.delete('/services/:id', protectAdmin, admin.deleteService);
router.post('/services/:id/image', protectAdmin, imageUpload.single('image'), admin.uploadServiceImage);
router.get('/activity-logs', protectAdmin, admin.activityLogs);
router.get('/availability/blocks', protectAdmin, admin.listAvailabilityBlocks);
router.post('/availability/blocks', protectAdmin, admin.createAvailabilityBlock);
router.delete('/availability/blocks/:id', protectAdmin, admin.deleteAvailabilityBlock);
router.get('/settings', protectAdmin, admin.getSettings);
router.patch('/settings', protectAdmin, admin.updateSettings);
export default router;
