import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Navbar from '../../layout/Navbar/Navbar';
import LuxuryFooter from '../../layout/Footer/footer';
import MediaImage from '../../components/MediaImage';
import { api } from '../../services/api';
import { money } from '../../utils/format';

export default function TherapistDetail() {
  const { id } = useParams();
  const [therapist, setTherapist] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { api.get(`/therapists/${id}`).then((r) => setTherapist(r.therapist)).catch((e) => setError(e.message)); }, [id]);
  if (error) return <div className="min-h-screen bg-[#fdfcf9]"><Navbar /><main className="mx-auto max-w-3xl px-6 pb-24 pt-40"><p className="text-red-600">{error}</p><Link to="/therapists" className="mt-6 inline-block text-xs tracking-[0.18em] text-[#b08d57]">← BACK TO THERAPISTS</Link></main><LuxuryFooter /></div>;
  if (!therapist) return <div className="min-h-screen bg-[#fdfcf9]"><Navbar /><main className="mx-auto max-w-7xl px-6 pb-24 pt-40"><div className="animate-pulse grid gap-8 lg:grid-cols-2"><div className="aspect-[4/5] bg-[#eee8df]"/><div className="space-y-5"><div className="h-5 w-32 bg-[#eee8df]"/><div className="h-12 w-2/3 bg-[#eee8df]"/><div className="h-20 bg-[#eee8df]"/></div></div></main></div>;
  return <div className="overflow-x-clip bg-[#fdfcf9]"><Navbar /><main className="px-6 pb-28 pt-36 sm:px-10 lg:px-12 lg:pt-44"><div className="mx-auto grid max-w-7xl items-start gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-20"><MediaImage src={therapist.profileImage} name={therapist.name} alt={`${therapist.name}, Aviana therapist`} wrapperClassName="aspect-[4/5] max-h-[760px]" className="h-full w-full object-cover"/><div className="lg:pt-8"><p className="text-[10px] uppercase tracking-[0.22em] text-[#b08d57]">Aviana Therapist · {therapist.gender === 'female' ? 'Woman' : 'Man'}</p><h1 className="mt-3 font-serif text-5xl font-light sm:text-6xl">{therapist.name}</h1><div className="mt-6 flex flex-wrap gap-3 text-xs text-[#7c725f]"><span className="border border-[#ded6ca] bg-white px-4 py-2">★ {Number(therapist.rating || 0).toFixed(1)}</span><span className="border border-[#ded6ca] bg-white px-4 py-2">{therapist.experience}+ years</span><span className="border border-[#ded6ca] bg-white px-4 py-2">{therapist.specialization}</span></div><p className="mt-8 max-w-2xl text-sm leading-8 text-[#7c725f]">{therapist.bio}</p><div className="mt-10"><h2 className="font-serif text-2xl">Specialisms</h2><div className="mt-4 flex flex-wrap gap-2">{(therapist.skills || []).map((skill) => <span key={skill} className="rounded-full bg-[#f2ede5] px-4 py-2 text-xs text-[#6f6659]">{skill}</span>)}</div></div><div className="mt-10"><h2 className="font-serif text-2xl">Services</h2><div className="mt-4 space-y-2">{(therapist.services || []).map((service) => <Link key={service._id || service.id} to={`/services/${service._id || service.id}?therapist=${therapist._id}`} className="flex items-center justify-between border-b border-[#e4ddd2] py-4 text-sm"><span>{service.title}</span><span className="text-[#8f7042]">{money(service.spaPrice)}</span></Link>)}</div></div><div className="mt-10 border border-[#ded6ca] bg-white p-6"><p className="text-[10px] uppercase tracking-[0.18em] text-[#b08d57]">Availability</p><p className="mt-3 text-sm leading-7 text-[#7c725f]">{therapist.availability?.shiftStart} – {therapist.availability?.shiftEnd}. Choose a date in the booking flow to see exact live slots.</p><Link to={`/booking?therapist=${therapist._id}&new=1`} className="mt-5 inline-flex bg-[#201e1a] px-6 py-4 text-[10px] tracking-[0.18em] text-white">BOOK WITH {therapist.name.split(' ')[0].toUpperCase()}</Link></div></div></div></main><LuxuryFooter /></div>;
}
