import { Menu, X } from 'lucide-react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { adminApi, useAdmin } from '../store/AdminContext';

const links = [['/admin','Overview'], ['/admin/users','Users'], ['/admin/bookings','Bookings'], ['/admin/payments','Payments'], ['/admin/therapists','Therapists'], ['/admin/services','Services'], ['/admin/extra-services','Extra Services'], ['/admin/booking-payment','Booking Payment'], ['/admin/availability','Availability'], ['/admin/activity-logs','Activity Logs'], ['/admin/settings','Settings']];
export default function AdminLayout({ children }) {
  const { admin, clear } = useAdmin(); const navigate = useNavigate(); const [open,setOpen]=useState(false);
  useEffect(()=>{setOpen(false)},[]);
  const logout = async () => { try { await adminApi.post('/auth/logout', {}); } finally { clear(); navigate('/admin/login'); } };
  return <div className="min-h-screen bg-[#151411] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#151411]/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><button type="button" onClick={()=>setOpen(true)} className="rounded-sm p-2 text-white/70 hover:bg-white/5 lg:hidden" aria-label="Open admin navigation"><Menu size={20}/></button><Link to="/admin" className="font-serif text-2xl tracking-[0.08em]">Aviana Admin</Link></div><div className="flex items-center gap-4"><span className="hidden text-xs text-white/50 sm:inline">{admin?.name}</span><button onClick={logout} className="text-[10px] tracking-[0.18em] text-white/60 hover:text-white">LOG OUT</button></div></div></header><div className="mx-auto grid max-w-[1500px] gap-8 px-5 py-7 sm:px-6 lg:grid-cols-[210px_minmax(0,1fr)]"><aside className="hidden lg:block"><AdminNav/></aside><main className="min-w-0">{children}</main></div>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/70" onClick={()=>setOpen(false)} aria-label="Close navigation overlay"/><aside className="relative h-full w-[280px] max-w-[88vw] bg-[#1a1814] p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-5"><Link to="/admin" onClick={()=>setOpen(false)} className="font-serif text-2xl">Aviana Admin</Link><button onClick={()=>setOpen(false)} className="p-2 text-white/70" aria-label="Close admin navigation"><X size={20}/></button></div><div className="mt-6"><AdminNav onNavigate={()=>setOpen(false)}/></div></aside></div>}</div>;
}
function AdminNav({onNavigate}) { return <nav className="space-y-1" aria-label="Admin"><>{links.map(([href,label])=><NavLink key={href} to={href} end={href==='/admin'} onClick={onNavigate} className={({isActive})=>`block rounded-sm px-3 py-3 text-xs tracking-[0.16em] ${isActive?'bg-[#b08d57] text-white':'text-white/55 hover:bg-white/5 hover:text-white'}`}>{label.toUpperCase()}</NavLink>)}</></nav>; }
