import { useEffect, useState } from 'react';
import AdminLayout from '../../layouts/AdminLayout';
import { adminApi } from '../../store/AdminContext';
import { prettyDate } from '../../utils/format';

export default function AdminAvailability() {
  const [blocks,setBlocks]=useState([]),[therapists,setTherapists]=useState([]),[form,setForm]=useState({date:'',therapist:'',startTime:'09:00',endTime:'20:00',reason:'Unavailable'}),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=async()=>{try{const [a,b]=await Promise.all([adminApi.get('/availability/blocks'),adminApi.get('/therapists')]);setBlocks(a.blocks||[]);setTherapists(b.therapists||[])}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[]);
  const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{await adminApi.post('/availability/blocks',form);setForm(v=>({...v,date:'',reason:'Unavailable'}));await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
  const remove=async id=>{try{await adminApi.delete(`/availability/blocks/${id}`);load()}catch(e){setError(e.message)}};
  return <AdminLayout><p className="text-[10px] uppercase tracking-[0.22em] text-[#b08d57]">Operations</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">Availability</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/45">Block an entire day/window or a single therapist. Booking availability always re-checks these records server-side.</p>{error&&<div className="mt-6 border border-red-400/20 bg-red-500/5 p-4 text-sm text-red-300">{error}</div>}<form onSubmit={submit} className="mt-8 grid gap-5 border border-white/10 bg-[#1d1b17] p-6 sm:grid-cols-2 xl:grid-cols-5"><Field label="Date" type="date" value={form.date} onChange={v=>setForm(x=>({...x,date:v}))} required/><label className="block"><span className="text-[10px] uppercase tracking-[0.16em] text-white/40">Therapist</span><select value={form.therapist} onChange={e=>setForm(v=>({...v,therapist:e.target.value}))} className="mt-2 w-full border-b border-white/10 bg-[#1d1b17] py-3 text-sm outline-none"><option value="">Entire spa</option>{therapists.map(t=><option key={t._id} value={t._id}>{t.name}</option>)}</select></label><Field label="Start" type="time" value={form.startTime} onChange={v=>setForm(x=>({...x,startTime:v}))} required/><Field label="End" type="time" value={form.endTime} onChange={v=>setForm(x=>({...x,endTime:v}))} required/><div><Field label="Reason" value={form.reason} onChange={v=>setForm(x=>({...x,reason:v}))}/><button disabled={saving} className="mt-4 min-h-11 w-full bg-[#b08d57] text-[10px] tracking-[0.18em] disabled:opacity-50">{saving?'BLOCKING…':'CREATE BLOCK'}</button></div></form><div className="mt-8 overflow-x-auto border border-white/10 bg-[#1d1b17]"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-white/10 text-[10px] uppercase tracking-[0.15em] text-white/40"><tr>{['Date','Therapist','Window','Reason',''].map((h,i)=><th key={i} className="p-4 font-normal">{h}</th>)}</tr></thead><tbody>{blocks.map(block=><tr key={block._id} className="border-b border-white/5 text-sm last:border-0"><td className="p-4">{prettyDate(block.date)}</td><td className="p-4">{block.therapist?.name||'Entire spa'}</td><td className="p-4">{block.startTime}–{block.endTime}</td><td className="p-4 text-white/55">{block.reason}</td><td className="p-4 text-right"><button onClick={()=>remove(block._id)} className="text-[10px] tracking-[0.14em] text-red-400">REMOVE</button></td></tr>)}{!blocks.length&&<tr><td colSpan="5" className="p-8 text-sm text-white/40">No availability blocks.</td></tr>}</tbody></table></div></AdminLayout>;
}
function Field({label,value,onChange,type='text',...props}){return <label className="block"><span className="text-[10px] uppercase tracking-[0.16em] text-white/40">{label}</span><input {...props} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full border-b border-white/10 bg-transparent py-3 text-sm outline-none focus:border-[#b08d57]"/></label>;}
